spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dorian?useSSL=false&createDatabaseIfNotExist=true&connectionCollation=utf8_unicode_520_ci&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: ${env:DB_USER}
    password: ${env:DB_PASSWORD}
