spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dorian?useSSL=false&createDatabaseIfNotExist=true&connectionCollation=utf8_unicode_520_ci&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: some_complex_password
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update

logging:
  config: classpath:logback-local.xml

management:
  endpoints:
    enabled-by-default: true
  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
